### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by r0xper** [alwaystest18/hbit#1]
docker部署以后启动时提示domain.txt打开失败
file open fail: domain.txt

**Comment by alwaystest18** [comment]
需要你本地在hbit目录下创建一个domain.txt，把要收集信息的域名每行一个写到里面，比如
aaa.com
bbb.com
这种

**Comment by r0xper** [comment]
那扫描出的结果会自动保存成excel还是txt文件

**Comment by r0xper** [comment]
在hbit更目录建了一个domain.txt 运行docker run -it --rm -v ./reports:/tools/hbit/reports -v ./domain.txt:/tools/hbit/domain.txt -v ./provider-config.yaml:/root/.config/subfinder/provider-config.yaml -v ./config/config.yaml:/tools/hbit/config/config.yaml hbit /bin/bash -c "cd /tools/hbit && ./hbit -df domain.txt" 确扫描不到任何资产信息

**Comment by r0xper** [comment]
在hbit更目录建了一个domain.txt 运行 docker run -it --rm -v ./reports:/tools/hbit/reports -v ./domain.txt:/tools/hbit/domain.txt -v ./ provider-config.yaml:/root/.config/subfinder/provider-config.yaml -v ./config/config.yaml:/tools/hbit/config/config.yaml hbit /bin/bash -c "cd /tools /hbit && ./hbit -df domain.txt" 确扫描不到任何资产信息

**Comment by alwaystest18** [comment]
能发个截图看看吗

**Comment by r0xper** [comment]
![1](https://github.com/alwaystest18/hbit/assets/6491913/82a20e27-5a7f-4016-bdc6-d71160b54b1e)

**Comment by r0xper** [comment]
![2](https://github.com/alwaystest18/hbit/assets/6491913/ebe40aac-9837-4e2f-99d5-cfb45db7f73f)

**Comment by alwaystest18** [comment]
方便留个联系方式吗，github沟通效率有点低。你这个问题很奇怪，感觉是有什么不可见字符，使程序最终解析到的不是baidu.com，否则不会没记录的

**Comment by r0xper** [comment]
x1aoboexp 微信
