### ISSUE TITLE
新需求

### ISSUE THREAD

**Issue by Zheisbug** [alwaystest18/hbit#2]
对于host碰撞这块。
场景：通过其他渠道获取的ip、domain但是hbit并没有收集到，我想给手工添加ip、domain进去，然后让程序继续走host碰撞程序，达到一个24小时实时监控host碰撞情况。

**Comment by alwaystest18** [comment]
host碰撞调用的是https://github.com/alwaystest18/hostCollision  ，你这个需求看起来可以直接单独使用host碰撞就行了
