### ISSUE TITLE
扫描不出任何结果

### ISSUE THREAD

**Issue by laaaaaaal** [alwaystest18/hbit#3]
<img width="601" alt="屏幕截图 2023-12-25 130841" src="https://github.com/alwaystest18/hbit/assets/154778426/92d91cec-6b40-4fc7-b506-9ac77045e01e">
<img width="485" alt="屏幕截图 2023-12-25 134447" src="https://github.com/alwaystest18/hbit/assets/154778426/6b765130-2787-4667-af78-b32847071cc8">
如图，使用docker阿里云的源安装，更改了绝对路径，确认没有不可见的字符任然没有结果

**Comment by alwaystest18** [comment]
domain.txt从你截图看内容是baidu.com
但是从你执行的截图看，你写的domain.txt内容应该是www.baidu.com
www.baidu.com下可能本来就找不到子域名了，你把domain.txt改成baidu.com试试
