### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by sys525** [alwaystest18/hbit#4]
docker: Error response from daemon: create ./reports: "./reports" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by alwaystest18** [comment]
目前已知kali下运行就会出现这种情况，其他系统可能也有类似的，把相对路径改为绝对路径启动就可以了
