### ISSUE TITLE
无隐藏字符，也尝试清除iptables规则重启docker还是不可以

### ISSUE THREAD

**Issue by sys525** [alwaystest18/hbit#6]
![屏幕截图 2024-05-24 151858](https://github.com/alwaystest18/hbit/assets/128903748/d047997d-0fd3-4cdc-9841-cbe90731ba03)

**Comment by alwaystest18** [comment]
之前遇到的大多数此类情况还是本地网络问题导致，比较大的可能是
1.docker内不能联网
2.有些网络限定只能使用内部的dns，所以使用工具提供的dns任何域名都解析不出来
可以进入到docker环境内，随便ping一个域名看看联网是否正常

**Comment by alwaystest18** [comment]
长时间无反馈，关闭
